### PR TITLE
Add check to see if ga is already loaded

### PR DESCRIPTION
**Pull request by tjjalava**

### CODE REVIEW

**Comment by nomasi** [comment]
This seems innocent enough for a release?

**Comment by tjjalava** [comment]
Check first with demo-site?

**Comment by nomasi** [comment]
https://stackoverflow.com/questions/29282313/check-if-analytics-js-is-loaded ?

**Comment by tjjalava** [comment]
we had that, but for some reason it didn't work (that https-issue) so I removed it. But that doesn't prevent multiple loading of analytics anyways

**Comment by nomasi** [comment]
ga('set', 'forceSSL', true); ?

if our analytics is always loaded via https, but the kookenkä live site is actually http?

**Comment by tjjalava** [comment]
hmm, maybe.. you mean the events won't work because we load analytics.js via https but send beacons with http?

**Comment by nomasi** [comment]
a wild guess.  just a shot in the dark.

**Pull request merged**
