### PR TITLE
GA tracking code namespaced

### PR DESCRIPTION
**Pull request by nomasi**
* as existing sites might have existing ga's?
* a guess at fixing the tracking problems at live Kookenkä

### CODE REVIEW

**Comment by nomasi** [comment]
And there seems to be a "too many parameters" warning, the prior fix to it (the let statements) was probably not the reason for our problems.

**Comment by tjjalava** [comment]
At kookenkä, I didn't notice any other scripts using google analytics, so I don't think it's a namespace problem. And even if they did use it, there shouldn't be any issues if multiple codebases use the same ga-function, at least according to the google docs. I'll dig into this later this evening

**Comment by nomasi** [comment]
They have Google Tag Manager which loads analytics I guess.  Maybe it's a matter of the https vs http issue? And maybe namespacing would help on that one?  

The kookenkä test site works just fine, so this is one tricky to debug.  We'll have another shot tomorrow morning at the live site.

**Comment by nomasi** [comment]
Wait.  The gaTrackingId is undefined in the live store. :(

**Comment by tjjalava** [comment]
I'm pretty sure our problems are some sort of timing issues. Usually ga is loaded first on a page, but we load it very late.

This plugin is btw very good for debugging ga: https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna

**Comment by nomasi** [comment]
The gaTrackingId doesn't have a value unless it's a demo store.  The plugin doesn't write a value for it as it assumed that the UA-40735596-1 was set by default.

**Pull request closed without merging**
